-- List all currently loaded modules
for k, v in pairs(package.loaded) do
  print(k)
end

-- Or list all packages that Lua can potentially require
for _, path in ipairs(package.path:split(";")) do
  print(path)
end

view.backend.snacks
lazy.core.handler.event
blink.cmp.config.completion.menu
blink.cmp.config.completion.accept
blink.cmp.config.completion.list
blink.cmp.config.completion.trigger
blink.cmp.config.completion.keyword
todo-comments.highlight
todo-comments.jump
todo-comments.config
telescope.algos.linked_list
gitsigns.config
snacks.scroll
noice.ui.msg
trouble
todo-comments
todo-comments.snacks
noice.text.format
lazyvim.util.inject
lazyvim.util.deprecated
blink.cmp.lib.term_events
blink.cmp.lib.cmdline_events
noice.api.status
blink.cmp.fuzzy.lua.keyword
editorconfig
blink.cmp.fuzzy.lua.match
trouble.tree
trouble.sort
which-key.text
snacks.util
lazy.manage.runner
snacks.explorer.watch
snacks.explorer.diagnostics
noice.message.manager
snacks.explorer
noice.ui.state
ts-comments.config
telescope.previewers.buffer_previewer
telescope.previewers.term_previewer
telescope.previewers.previewer
blink.cmp.types
blink.cmp.keymap.presets
noice.view.backend.split
lazy.manage.task
lazy.pkg
lazy.core.meta
snacks.input
bufferline.constants
bufferline.colors
lazydev
nui.utils
nui.object
fzf_lib
blink_cmp_fuzzy
blink.cmp.fuzzy.lua.char
vim.lsp.util
nvim-treesitter
mini.ai
lazy.terminal
blink.cmp.keymap.apply
lazy.manage.semver
snacks.scope
bufferline.models
mini.pairs
lazy.util
lazy.manage.checker
lazy.core.plugin
telescope.actions.state
telescope.builtin
lazy.manage.reloader
trouble.sources.telescope
noice.util.nui
noice.util.call
noice.util.stats
_G
noice
gitsigns
string
table
lazyvim.config.options
plenary.async
telescope.actions
config.options
which-key.plugins.registers
snacks.explorer.tree
snacks.explorer.actions
which-key
snacks.picker
plenary.async.async
plenary.async.tests
plenary.async.util
plenary.async.control
lazyvim.util.plugin
telescope.make_entry
telescope.finders
snacks.picker.core.picker
which-key.plugins.spelling
snacks.picker.config
vim.lsp.sync
plenary.errors
plenary.vararg
gitsigns.util
gitsigns.manager
gitsigns.status
which-key.plugins.marks
vim.lsp.rpc
plenary.vararg.rotate
noice.integrations.snacks
noice.config.cmdline
noice.config.preset
snacks.picker.config.layouts
telescope.utils
snacks.picker.config.sources
telescope.finders.async_job_finder
telescope.finders.async_oneshot_finder
telescope.finders.async_static_finder
vim.lsp
snacks.picker.core.finder
snacks.picker.sort
plenary.tbl
snacks.picker.config.highlights
which-key.plugins.presets
trouble.sources.diagnostics
nvim-ts-autotag.config.plugin
gitsigns.hunks
noice.lsp.progress
noice.lsp.signature
telescope.algos.fzy
gitsigns.git.repo
vim.lsp.buf
nvim-treesitter.textobjects.swap
noice.ui.popupmenu
trouble.sources.fzf
telescope.log
vim.lsp._transport
nvim-ts-autotag.config.ft
vim.treesitter.highlighter
nvim-ts-autotag.utils
nvim-ts-autotag.config.init
nvim-ts-autotag._log
plenary.path
telescope.sorters
telescope.deprecated
nvim-treesitter.textobjects.shared
telescope.pickers.multi
telescope.entry_manager
telescope.pickers.layout
telescope.pickers.window
telescope.pickers.highlights
telescope.mappings
telescope.debounce
lualine.component
trouble.view.render
conform.fs
telescope.command
conform.ft_to_ext
blink.cmp.completion.trigger.context
vim.lsp.codelens
plenary.scandir
coroutine
nvim-treesitter.textobjects.repeatable_move
vim._system
lazydev.config
lazydev.workspace
trouble.view.text
trouble.view.indent
trouble.format
trouble.cache
nui.line
noice.text.highlight
gitsigns.git
gitsigns.cache
plenary.functional
plenary.bit
lazyvim.util.cmp
lazydev.buf
lazydev.util
gitsigns.debounce
gitsigns.attach
lualine.utils.mode
io
lualine.utils.nvim_opts
lualine.config
lualine.utils.section
lualine.highlight
gitsigns.highlight
gitsigns.debug.log
gitsigns.async
vim.snippet
conform
os
nui.layout.utils
vim.treesitter._range
snacks.quickfile
telescope._extensions.fzf
config.keymaps
string.buffer
math
lazyvim.util.format
snacks.bigfile
plenary.async.structs
snacks.indent
noice.view.backend.popup
which-key.triggers
nvim-treesitter.compat
nvim-treesitter.shell_command_selectors
nvim-treesitter.parsers
lazyvim
lualine.components.branch
lint
vim.ui
debug
trouble.spec
trouble.config.actions
nvim-treesitter.statusline
telescope.config.resolve
lualine.components.branch.git_branch
telescope.actions.mt
which-key.tree
telescope.pickers.entry_display
telescope.actions.set
telescope.actions.utils
telescope.pickers.scroller
plenary.popup
telescope.state
snacks.picker.actions
snacks
telescope._
lazyvim.config
lualine.utils.class
vim.lsp._changetracking
which-key.node
config.keymap_funcs
lazyvim.plugins.lsp.keymaps
telescope.actions.history
telescope.previewers
lualine.components.filename
lspconfig
lspconfig.util
snacks.picker.core.score
plenary.class
blink.cmp.fuzzy.rust
lazyvim.util.news
nvim-treesitter.indent
lua-timeago
nvim-treesitter.incremental_selection
nvim-treesitter.highlight
lualine.extensions.neo-tree
nvim-treesitter.caching
lazyvim.util.root
lualine.extensions.nerdtree
blink.cmp.fuzzy.download.system
blink.cmp.fuzzy.download.files
gitblame
which-key.util
which-key.state
snacks.picker.core.preview
snacks.statuscolumn
snacks.picker.core.list
lazy.core.util
snacks.dashboard
snacks.layout
snacks.picker.core.actions
snacks.picker.core.main
trouble.config
trouble.api
snacks.picker.util.history
lazy.core.cache
which-key.view
lualine.extensions.fzf
lazy.stats
nvim-treesitter.tsrange
nvim-treesitter.query_predicates
nvim-treesitter.configs
snacks.toggle
nvim-treesitter.textobjects.move
trouble.view
trouble.view.main
trouble.config.highlights
lspconfig.configs
trouble.util
lazydev.pkg
trouble.sources
lazy.view.commands
lazy
snacks.picker.format
gitblame.config
snacks.picker.util.async
snacks.picker.source.explorer
nvim-treesitter.ts_utils
gitblame.utils
gitblame.git
blink.cmp.commands
blink.cmp.completion
blink.cmp.keymap
blink.cmp.highlights
blink.cmp.fuzzy
nvim-treesitter-textobjects
blink.cmp.fuzzy.download
vim.lsp.diagnostic
nvim-ts-autotag
persistence.config
lspconfig.manager
blink.cmp.completion.trigger
snacks.notifier
lazyvim.util.mini
lspconfig.async
trouble.sources.lsp
bufferline
bufferline.ui
blink.cmp.sources.lib
vim.F
noice.view.scrollbar
lualine.components.mode
telescope.pickers
noice.text.treesitter
blink.cmp.config.sources
conform.log
trouble.item
lspconfig.configs.pyright
trouble.filter
luv
vim.treesitter
conform.runner
blink.cmp.config.modes.term
snacks.explorer.git
which-key.win
which-key.layout
lazyvim.util.lualine
which-key.icons
lazy.status
nui.utils.keymap
nui.popup.border
bufferline.lazy
noice.util.spinners
conform.lsp_format
snacks.words
vim.lsp.semantic_tokens
lazydev.integrations
lazydev.lsp
noice.util.ffi
vim.lsp.client
lualine_require
vim.lsp._snippet_grammar
snacks.win
lazy.core.fragments
snacks.picker.util.minheap
nvim-treesitter.utils
lualine.utils.loader
vim.lsp.protocol
noice.lsp
snacks.picker.core.filter
trouble.view.window
nvim-web-devicons
conform.errors
mini.icons
lualine.utils.utils
gitsigns.git.version
trouble.promise
plenary.log
ts-comments
conform.util
lualine.components.diagnostics
lualine.components.filetype
snacks.picker.source.git
blink.cmp.fuzzy.download.git
snacks.git
blink.cmp.config
vim._defaults
snacks.profiler
noice.view.backend.notify_send
vim._options
lspconfig.configs.lua_ls
snacks.picker.core.input
conform.formatters.stylua
blink.cmp.config.utils
lazy.core.config
trouble.sources.qf
telescope.config
lazyvim.util.lsp
snacks.picker.util
package
snacks.picker.util.kv
snacks.picker.util.highlight
vim.treesitter._fold
lualine.components.progress
nvim-ts-autotag.internal
lazy.core.handler.keys
vim.treesitter.languagetree
lazyvim.util
lualine.components.diagnostics.sources
lualine.components.diagnostics.config
which-key.config
telescope
telescope.from_entry
blink.cmp.lib.event_emitter
blink.cmp.lib.utils
blink.cmp.lib.async
lazy.manage
noice.api
noice.view.backend.mini
noice.config.icons
bufferline.utils
noice.ui.cmdline
lualine.components.location
nvim-treesitter.textobjects.lsp_interop
snacks.picker.preview
vim.diagnostic
trouble.sources.profiler
telescope.themes
gitsigns.system
gitsigns.git.cmd
noice.text
noice.text.markdown
mpack
lazy.health
lazy.core.handler.cmd
lpeg
bit
lazyvim.config.autocmds
config.autocmds
vim.lsp.log
noice.view.nui
vim.lsp.inlay_hint
lazy.async
vim.lsp.handlers
telescope._extensions
lazy.core.loader
trouble.sources.snacks
lazy.core.handler.ft
vim.uri
ffi
vim._init_packages
vim._editor
noice.text.format.formatters
jit
jit.opt
lualine.utils.fn_store
bufferline.highlights
lua-timeago/languages/en
bufferline.hover
lualine.components.diff.git_diff
nui.popup
nui.split
vim.iter
nvim-treesitter.locals
blink.cmp.config.modes.cmdline
blink.cmp.config.appearance
blink.cmp.config.snippets
blink.cmp.config.signature
bufferline.tabpages
blink.cmp.config.completion
bufferline.buffers
bufferline.sorters
bufferline.config
bufferline.groups
bufferline.offset
bufferline.custom_area
bufferline.numbers
bufferline.duplicates
bufferline.diagnostics
vim.shared
vim.loader
vim.keymap
bufferline.commands
vim.fs
vim.filetype
vim.treesitter.query
vim.inspect
plenary.job
trouble.view.preview
gitsigns.message
plenary.strings
lualine.components.special.function_component
vim._inspector
nvim-treesitter.textobjects.select
nvim-treesitter.textobjects.attach
lazyvim.config.keymaps
nui.split.utils
vim.func
noice.message.router
noice.commands
noice.config
noice.util
noice.util.hacks
noice.ui
noice.source.notify
noice.config.format
noice.health
vim.lsp.completion
telescope.builtin.__files
lazyvim.util.ui
noice.config.routes
lazy.state
vim.version
vim.func._memoize
melange/palettes/dark
noice.config.status
lualine.components.diff
nvim-treesitter.install
noice.config.views
snacks.picker.config.defaults
noice.config.highlights
noice.message
noice.text.block
noice.message.filter
telescope.pickers.layout_strategies
todo-comments.util
nui.text
bufferline.state
persistence
vim.health
blink.cmp
bufferline.pick
gitsigns.current_line_blame
blink.cmp.config.completion.documentation
gitsigns.diff
blink.cmp.config.completion.ghost_text
blink.cmp.config.fuzzy
snacks.picker.core.matcher
blink.cmp.config.modes.types
which-key.colors
which-key.plugins
which-key.mappings
lazy.manage.git
noice.lsp.message
noice.lsp.override
lspconfig.configs.djlsp
which-key.presets
noice.util.lazy
nvim-treesitter.info
nvim-treesitter.query
lualine
which-key.buf
snacks.animate
lualine.extensions.lazy
lazy.manage.process
blink.cmp.config.keymap
vim.hl
blink.cmp.fuzzy.lua
blink.cmp.fuzzy.lua.match_indices
blink.cmp.lib.buffer_events
blink.cmp.completion.list
trouble.view.section
lazyvim.util.pick
